name: input_country_example
description: Example to show selction widgets for country, currency and language

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  input_country:
    path: ../

flutter:
  uses-material-design: true
