name: input_country_example
description: Example to show selction widgets for country, currency and language.
 Includes platform language setting.
version: 2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  input_country:
    path: ../

flutter:
  uses-material-design: true
