# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Disables warnings 'to not specify local variable type'
linter:
  rules:
    omit_local_variable_types: false
    always_specify_types: true

dependency:
  include: package:pedantic/analysis_options.yaml

analyzer:
#   exclude:
#     - path/to/excluded/files/**
