name: input_country
description: Countries (ISO-3166), Languages (ISO-639) and Currencies (ISO-4217) with choosers (DropdownButton) and flag images
homepage: https://github.com/djarjo/input_country
version: 2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/flags/